### ISSUE TITLE
Remove no background option from alerts

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1456]
### Description

we still have 

```css
.no-background {
  background-color: color.$white;
  border-left-color: color.$white;
}
```

this work has already been removed so we can get rid of that logic in the component

### Acceptance Criteria

- [ ] no background is no longer part of the component api or style sheet
